import type { InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getStaticProps } from "./_app";

function BlogPages({ posts }: InferGetStaticPropsType<typeof getStaticProps>) {
  return <h2>{posts}</h2>;
}

function Home({ posts }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div className={styles.container}>
      <Head>
        <title>kanium blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlogPages posts={posts}></BlogPages>
    </div>
  );
}

export default Home;
