import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getContentFilesInDirectory } from './api/blogs'

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>kanium blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		<p>{getContentFilesInDirectory().toString()}</p>
		</div>
	)
}

export default Home
